### PR TITLE
Add explicit ordering for record types and boundaries

### PR DESCRIPTION
**Pull request by flibbertigibbet**

### CODE REVIEW

**Comment by kshepard** [comment]
+1. Did you try running makemigrations? I think Django might create one here even though it won't change the db. Commit the migration if it creates one.

**Comment by flibbertigibbet** [comment]
This is a change to `views.py`, not `models.py`. I don't think migrations should be involved.

**Comment by flibbertigibbet** [comment]
Running `makemigrations` from the DRIVER script, it says 'No changes detected'.

**Comment by kshepard** [comment]
Oh, right, nevermind. Thanks for checking anyway!

**Comment by flibbertigibbet** [comment]
@moradology might want to double-check the test fix here. There was a comment saying there's only one result, but then it indexed the second result; changing it to reference the first fixes the test. It's unclear how adding ordering to seeming unrelated models would affect the toddow query result order.

**Pull request merged**
